# -*- coding: utf-8 -*-
"""Advanced_python_merge_demographics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5ib453CCJ9DVx98TJT8E6xij4rPAvVS
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy

diabetes_filepath = '/content/drive/My Drive/Colab Notebooks/Demographics/DIQ_L.xpt'
df_d = pd.read_sas(diabetes_filepath,format='xport')
print(df_d.head())
print(df_d.count())

df_d = df_d.rename(columns={'DIQ010':'Diabetes'})
d = df_d[['SEQN','Diabetes']]
print(d.head())

health_insurance_filepath = '/content/drive/My Drive/Colab Notebooks/Demographics/HIQ_L.xpt'
df_hi = pd.read_sas(health_insurance_filepath,format='xport')
print(df_hi.head())
print(df_hi.count())

Plasma_fasting_glucose_filepath = '/content/drive/My Drive/Colab Notebooks/laboratory/GLU_L.xpt'
df_pg = pd.read_sas(Plasma_fasting_glucose_filepath,format='xport')
print(df_pg.head())
print(df_pg.count())

df_pg = df_pg.rename(columns={'LBXGLU':'Fasting_Glucose_mg/DL'})
pg = df_pg[['SEQN','Fasting_Glucose_mg/DL']]
print(pg.head())

insulin_filepath = '/content/drive/My Drive/Colab Notebooks/laboratory/INS_L.xpt'
df_in = pd.read_sas(insulin_filepath,format='xport')
print(df_in.head())
print(df_in.count())

df_in = df_in.rename(columns={'LBXIN':'Insulin_uU/mL'})
inn = df_in[['SEQN','Insulin_uU/mL']]
print(inn.head())

glycohemoglobin_filepath = '/content/drive/My Drive/Colab Notebooks/laboratory/GHB_L.xpt'
df_gh = pd.read_sas(glycohemoglobin_filepath,format='xport')
print(df_gh.head())
print(df_gh.count())

df_gh = df_gh.rename(columns={'LBXGH':'Glycohemoglobin_%'})
gh = df_gh[['SEQN','Glycohemoglobin_%']]
print(gh.head())

albumin_creatinine_filepath = '/content/drive/My Drive/Colab Notebooks/laboratory/ALB_CR_L.xpt'
df_ac = pd.read_sas(albumin_creatinine_filepath,format='xport')
print(df_ac.head())
print(df_ac.count())

df_ac = df_ac.rename(columns={'URXUMA':'Albumin_urine_ug/mL'})
ac = df_ac[['SEQN','Albumin_urine_ug/mL']]
print(ac.head())

fasting_questionnaire_filepath = '/content/drive/My Drive/Colab Notebooks/laboratory/ALB_CR_L.xpt'
df_fq = pd.read_sas(fasting_questionnaire_filepath,format='xport')
print(df_fq.head())
print(df_fq.count())

pg_inn = pd.merge(pg,inn,on='SEQN',how='inner')
print(pg_inn.count())

pg_inn_gh = pd.merge(pg_inn,gh,on='SEQN',how='inner')
print(pg_inn_gh.count())

pg_inn_gh_ac = pd.merge(pg_inn_gh,ac,on='SEQN',how='inner')
print(pg_inn_gh_ac.count())

d_pg_inn_gh_ac = pd.merge(pg_inn_gh_ac,d,on='SEQN',how='inner')
print(d_pg_inn_gh_ac.count())

print(d_pg_inn_gh_ac.head())

print(d_pg_inn_gh_ac.describe())

print(d_pg_inn_gh_ac['Diabetes'].value_counts())

total_nans = d_pg_inn_gh_ac.isna().sum()
print(total_nans)

d_pg_inn_gh_ac.to_csv('/content/drive/My Drive/Colab Notebooks/laboratory/lab_data.csv')

d_pg_inn_gh_ac.to_excel('/content/drive/My Drive/Colab Notebooks/laboratory/lab_data.xlsx',index= False)



df_questionaire = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Questionnaire/NHANES_Questionairre_data_Merged.csv')

df_questionaire.info()

df_questionaire.isna().sum()

col = df_questionaire.columns [df_questionaire.isnull().sum()>5000]
col

df_q_clean = df_questionaire.drop(columns=col)
df_q_clean.isna().sum()

import io
import pandas as pd
dd = pd.read_csv(io.StringIO('''
MealsDelivered_CommunityGov,MealsAt_SeniorCenter,SchoolLunch_PriceType,SchoolBreakfast_ServedDaily,TimesPerWeek_Breakfast,MainMeal_Planner,Shared_MealPlanning,MainFood_Shopper,Shared_ShoppingDuty
'''), header=None)
dd = dd.iloc[0].tolist()
dd

present = [col for col in dd if col in df_q_clean.columns]
present

df_q = df_q_clean.drop(columns = present)
df_q.isna().sum()

df_lab_q = pd.merge(d_pg_inn_gh_ac,df_q,on='SEQN',how='inner')
df_lab_q.describe()

df_lab_q.to_excel('/content/drive/My Drive/Colab Notebooks/laboratory/lab_q_data.xlsx',index= False)

list1 = df_lab_q.columns
for i in list1:
  print(i)

print(len(list1))

cov_col = ['SEQN','Diabetes','Fasting_Glucose_mg/DL','Glycohemoglobin_%','HighBP_Ever','Diabetes_Risk_Flag','HighChol_Ever','On_CholMeds','Insulin_uU/mL']
#print(len(cov_col))
new_df = df_lab_q[cov_col]
print(new_df.columns)

new_df.info()

df_lab_q['Diabetes'].value_counts()

# fill the missing values with the median data
df_val_filled = df_lab_q[cov_col].fillna(df_lab_q[cov_col].median())

#dropping the rows without the data
df_row_dropped = df_lab_q.dropna(subset=cov_col)
df_row_dropped = df_row_dropped[cov_col]
df_row_dropped.info()

df_val_filled.info()

from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

X = df_row_dropped.drop(columns=['Diabetes'])   # features
y = df_row_dropped['Diabetes']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = Perceptron(random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap="Blues")

X = df_val_filled.drop(columns=['Diabetes'])   # features
y = df_val_filled['Diabetes']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = Perceptron(random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

cm1 = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm1)
disp.plot(cmap="Blues")

df_row_dropped['Diabetes'] = df_row_dropped['Diabetes'].replace(3, 1)
X = df_row_dropped.drop(columns=['Diabetes'])   # features
y = df_row_dropped['Diabetes']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = Perceptron(random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap="Blues")

from sklearn.metrics import precision_score, recall_score
precision = precision_score(y_test, y_pred)
print(precision)

recall = recall_score(y_test, y_pred)
print(recall)